version: '2'
services:
    oplusjat-app:
        image: oplusjat
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://oplusjat-mysql:3306/oplusjat?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
    oplusjat-mysql:
        extends:
            file: mysql.yml
            service: oplusjat-mysql
